<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>Graphic Designer Portfolio</title>
<style>
*{margin:0;padding:0;box-sizing:border-box}html{scroll-behavior:smooth}body{font-family:Inter,Segoe UI,sans-serif;color:#2c3e50;line-height:1.6;background:linear-gradient(180deg,#f8f9fa 0%,#e8eef7 100%);overflow-x:hidden}.container{width:90%;max-width:1200px;margin:0 auto;padding:20px}:root{--dark:#0a0e27;--blue:#3498db;--gold:#f39c12;--light:#fff;--shadow:0 10px 40px rgba(0,0,0,.1);--t:all .3s ease}
header{position:sticky;top:0;z-index:1000;background:rgba(10,14,39,.95);backdrop-filter:blur(10px);padding:15px 0;box-shadow:0 4px 20px rgba(0,0,0,.1)}.header-container{display:flex;justify-content:space-between;align-items:center;width:90%;max-width:1200px;margin:0 auto;padding:10px 20px}.logo{font-size:1.5rem;font-weight:700;letter-spacing:2px;background:linear-gradient(135deg,var(--blue),var(--gold));-webkit-background-clip:text;-webkit-text-fill-color:transparent}.menu-toggle{display:none;flex-direction:column;gap:6px;cursor:pointer}.menu-toggle span{width:25px;height:3px;background:#fff;border-radius:2px}
nav{display:flex;gap:30px}nav a{color:#fff;text-decoration:none;font-size:.9rem;font-weight:500;text-transform:uppercase;position:relative}nav a::after{content:'';position:absolute;left:0;bottom:-5px;width:0;height:2px;background:var(--gold);transition:width .3s}nav a:hover::after{width:100%}
.hero{position:relative;overflow:hidden;text-align:center;padding:80px 20px;background:linear-gradient(135deg,var(--dark) 0%,#2c3e50 100%);color:#fff}.hero::before{content:'';position:absolute;inset:0;background:radial-gradient(circle at 20% 50%,rgba(52,152,219,.1),transparent 50%),radial-gradient(circle at 80% 80%,rgba(243,156,18,.1),transparent 50%);pointer-events:none}.hero-content{position:relative;z-index:2}.hero h1{font-size:3.5rem;margin-bottom:20px;letter-spacing:2px;text-transform:uppercase;font-weight:800;background:linear-gradient(135deg,var(--blue),var(--gold));-webkit-background-clip:text;-webkit-text-fill-color:transparent;line-height:1.2}.hero p{font-size:1.3rem;opacity:.9;margin-bottom:30px;font-weight:300}.cta-button{display:inline-block;padding:15px 40px;background:var(--gold);color:var(--dark);text-decoration:none;border-radius:50px;font-weight:700;text-transform:uppercase;letter-spacing:1px;border:none;cursor:pointer;transition:var(--t);box-shadow:0 10px 30px rgba(243,156,18,.3)}.cta-button:hover{transform:translateY(-3px);box-shadow:0 15px 40px rgba(243,156,18,.4)}
section{margin:60px 0;padding:0 20px}section h2{font-size:2.2rem;margin-bottom:40px;color:var(--dark);text-transform:uppercase;letter-spacing:1.5px;position:relative;display:inline-block;padding-bottom:20px}section h2::after{content:'';position:absolute;left:0;bottom:0;width:60px;height:4px;background:linear-gradient(90deg,var(--blue),var(--gold));border-radius:2px}
.services-grid,.portfolio-grid{display:grid;gap:30px;margin:50px 0}.services-grid{grid-template-columns:repeat(auto-fit,minmax(280px,1fr))}.portfolio-grid{grid-template-columns:repeat(auto-fit,minmax(300px,1fr))}.card,.project-card,.contact-section{background:#fff;border-radius:12px;box-shadow:var(--shadow)}.card{padding:40px;position:relative;overflow:hidden;cursor:pointer;border-left:5px solid var(--blue);transition:var(--t)}.card:hover{transform:translateY(-15px);box-shadow:0 20px 50px rgba(0,0,0,.15);border-left-color:var(--gold)}.card-icon{font-size:3rem;margin-bottom:15px;display:inline-block}.card h3,.project-info h4{color:var(--dark);text-transform:uppercase}.card h3{margin-bottom:15px;font-size:1.3rem}.card p,.project-info p{color:#666}.card p{font-size:.95rem;line-height:1.8}
.project-card{overflow:hidden;transition:var(--t);position:relative}.project-card::before{content:attr(data-tech);position:absolute;top:15px;right:15px;background:var(--blue);color:#fff;padding:5px 15px;border-radius:20px;font-size:.75rem;font-weight:600;text-transform:uppercase;z-index:10;opacity:0;transform:translateY(-10px);transition:var(--t)}.project-card:hover::before{opacity:1;transform:translateY(0)}.project-card:hover{transform:translateY(-10px);box-shadow:0 20px 50px rgba(52,152,219,.2)}.project-image{height:200px;background:linear-gradient(135deg,var(--blue),var(--gold));display:flex;align-items:center;justify-content:center;font-size:2.5rem;color:#fff;transition:var(--t)}.project-card:hover .project-image{transform:scale(1.05)}.project-info{padding:20px}.project-info h4{margin-bottom:10px;font-size:1.1rem}.project-info p{font-size:.9rem;margin-bottom:15px}.project-link{color:var(--blue);text-decoration:none;font-weight:600;font-size:.85rem;text-transform:uppercase}.project-link:hover{color:var(--gold)}
.contact-section{padding:50px;margin:60px 0}.form-group{margin-bottom:25px}.form-group label{display:block;margin-bottom:8px;color:var(--dark);font-weight:600;text-transform:uppercase;font-size:.85rem;letter-spacing:.5px}input,textarea,select{width:100%;padding:14px 18px;border:2px solid #e0e0e0;border-radius:6px;font:inherit;font-size:1rem;background:#f8f9fa;transition:var(--t)}input:focus,textarea:focus,select:focus{outline:none;border-color:var(--blue);background:#fff;box-shadow:0 0 0 3px rgba(52,152,219,.1)}textarea{resize:vertical;min-height:120px}.form-validation{font-size:.75rem;color:#d32f2f;margin-top:5px;display:none}.form-validation.show,.success-message.show{display:block}.success-message{display:none;background:#4caf50;color:#fff;padding:15px;border-radius:6px;margin-bottom:20px}
footer{text-align:center;padding:50px 20px;color:#666;border-top:1px solid #e0e0e0;background:rgba(255,255,255,.5)}footer p{margin:8px 0}footer a{color:var(--blue);text-decoration:none}footer a:hover{color:var(--gold)}
.fade-in{animation:fadeInScale .6s ease-out forwards;opacity:0}.fade-in-1{animation-delay:.1s}.fade-in-2{animation-delay:.2s}.fade-in-3{animation-delay:.3s}.fade-in-4{animation-delay:.4s}@keyframes fadeInScale{from{opacity:0;transform:scale(.9)}to{opacity:1;transform:scale(1)}}
@media (max-width:768px){.menu-toggle{display:flex}nav{display:none;position:absolute;top:100%;right:0;flex-direction:column;background:var(--dark);padding:20px;gap:15px;width:100%}nav.active{display:flex}.hero h1{font-size:2.5rem}.hero p{font-size:1.1rem}section h2{font-size:1.8rem}.services-grid,.portfolio-grid{grid-template-columns:1fr}.contact-section{padding:30px 20px}}
@media (max-width:480px){.header-container{width:100%;padding:10px 15px}.logo{font-size:1.2rem}.hero h1{font-size:2rem}.hero p{font-size:1rem}section h2{font-size:1.5rem}.cta-button{width:100%;padding:12px 20px}}
</style>
</head>
<body>
<header><div class="header-container"><div class="logo">DESIGN</div><nav id="navigation"><a href="#home">Home</a><a href="#overview">Overview</a><a href="#expertise">Expertise</a><a href="#portfolio">Portfolio</a><a href="#contact">Contact</a></nav><div class="menu-toggle" id="menuToggle"><span></span><span></span><span></span></div></div></header>
<section class="hero" id="home"><div class="container"><div class="hero-content"><h1>CREATIVE DESIGN SOLUTIONS</h1><p>Transforming Ideas Into Visual Masterpieces</p><button class="cta-button" onclick="document.getElementById('contact').scrollIntoView({behavior:'smooth'})">Start Your Project</button></div></div></section>
<section id="overview"><div class="container"><h2>Project Overview</h2><p><strong>Objective:</strong> Create a clean, responsive, interactive portfolio that showcases design expertise with smooth animations and user engagement.</p><p><strong>Technology Stack:</strong> Advanced HTML5, CSS3 with animations, and vanilla JavaScript for interactivity.</p><p><strong>Key Features:</strong> Sticky navigation, form validation, scroll animations, mobile responsiveness, and smooth transitions.</p></div></section>
<section id="expertise"><div class="container"><h2>Core Expertise</h2><div class="services-grid"><div class="card fade-in fade-in-1"><div class="card-icon">🎨</div><h3>Logo Design</h3><p>Create memorable brand identities that tell your story and leave lasting impressions.</p></div><div class="card fade-in fade-in-2"><div class="card-icon">📄</div><h3>Stationery</h3><p>Professional business cards, letterheads, and corporate kits that reflect your brand.</p></div><div class="card fade-in fade-in-3"><div class="card-icon">📱</div><h3>Social Media</h3><p>Engaging Instagram, Facebook, and LinkedIn graphics that boost engagement.</p></div><div class="card fade-in fade-in-4"><div class="card-icon">✨</div><h3>UI/UX Design</h3><p>Modern web and mobile app layouts designed for optimal user experience.</p></div></div></div></section>
<section class="portfolio-section" id="portfolio"><div class="container"><h2>Portfolio Projects</h2><div class="portfolio-grid"><div class="project-card" data-tech="Branding"><div class="project-image">🏢</div><div class="project-info"><h4>Corporate Identity</h4><p>Complete brand guidelines and visual system for Fortune 500 company.</p><a href="#" class="project-link">View Case Study →</a></div></div><div class="project-card" data-tech="Web Design"><div class="project-image">🌐</div><div class="project-info"><h4>E-Commerce Platform</h4><p>Modern web design with conversion-focused UX and interactive elements.</p><a href="#" class="project-link">View Case Study →</a></div></div><div class="project-card" data-tech="Social Media"><div class="project-image">📊</div><div class="project-info"><h4>Social Campaign</h4><p>Viral social media graphics and content strategy for tech startup.</p><a href="#" class="project-link">View Case Study →</a></div></div></div></div></section>
<section id="contact"><div class="container"><section class="contact-section"><h2>Get In Touch</h2><div class="success-message" id="successMessage">✓ Thank you! Your inquiry has been received. We'll be in touch within 24 hours.</div><form id="contactForm" novalidate><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:20px;margin-bottom:20px;"><div class="form-group"><label for="fullName">Full Name</label><input type="text" id="fullName" required><div class="form-validation" id="nameError">Please enter your full name</div></div><div class="form-group"><label for="email">Email Address</label><input type="email" id="email" required><div class="form-validation" id="emailError">Please enter a valid email address</div></div></div><div class="form-group"><label for="projectType">Project Type</label><select id="projectType"><option value="">-- Select Project Type --</option><option>Logo Design</option><option>Web Design</option><option>Social Media Graphics</option><option>Complete Branding</option><option>Other</option></select></div><div class="form-group"><label for="projectDetails">Project Details</label><textarea id="projectDetails" required></textarea><div class="form-validation" id="detailsError">Please provide project details</div></div><button type="submit" class="cta-button">Send Inquiry</button></form></section></div></section>
<footer><p>© 2026 Creative Design Studio | All Rights Reserved</p><p>Crafted with precision and passion for modern brands</p><p><a href="#">Privacy Policy</a> | <a href="#">Terms of Service</a> | <a href="#">Sitemap</a></p></footer>
<script>
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s),nav=$('#navigation'),menu=$('#menuToggle'),form=$('#contactForm'),msg=$('#successMessage');
menu.onclick=()=>{nav.classList.toggle('active');menu.classList.toggle('active')};$$('nav a').forEach(a=>a.onclick=()=>{nav.classList.remove('active');menu.classList.remove('active')});
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('fade-in');io.unobserve(e.target)}}),{threshold:.1,rootMargin:'0px 0px -50px 0px'});$$('.card').forEach(c=>io.observe(c));
const emailOk=v=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v),show=(id,on)=>$(id).classList.toggle('show',on);
function validate(){let ok=1,n=$('#fullName'),e=$('#email'),d=$('#projectDetails');show('#nameError',n.value.trim().length<3);show('#emailError',!emailOk(e.value));show('#detailsError',d.value.trim().length<10);[n,e,d].forEach(x=>x.style.borderColor='#e0e0e0');if(n.value.trim().length<3||!emailOk(e.value)||d.value.trim().length<10) ok=0;return ok}
form.onsubmit=a=>{a.preventDefault();if(validate()){msg.classList.add('show');form.reset();setTimeout(()=>msg.classList.remove('show'),5000);msg.scrollIntoView({behavior:'smooth',block:'center'})}};
$$('a[href^="#"]').forEach(a=>a.onclick=function(e){e.preventDefault();const t=document.querySelector(this.getAttribute('href'));t&&t.scrollIntoView({behavior:'smooth'})});
window.onscroll=()=>document.querySelector('header').style.boxShadow=window.scrollY?'0 4px 20px rgba(0,0,0,.15)':'0 4px 20px rgba(0,0,0,.1)';
window.addEventListener('DOMContentLoaded',()=>{$$('.project-card').forEach((c,i)=>{c.style.opacity=0;c.style.transform='translateY(20px)';setTimeout(()=>{c.style.transition='all .6s ease-out';c.style.opacity=1;c.style.transform='translateY(0)'},i*150)})});
</script>
</body>
</html>'''
print(len(html.splitlines()))
with open('output/portfolio_short.html','w',encoding='utf-8') as f:
    f.write(html)
